#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

export RUNLIMIT_INCLUDE="${RUNLIMIT_INCLUDE-/usr/local/lib}"

MACHTYPE="$(uname -m)"
case "${MACHTYPE}" in
  armv6l) ;&
  armv7l) MACHTYPE=arm ;;
  *) ;;
esac

RUNLIMIT_LDFLAGS="-I$RUNLIMIT_INCLUDE/kernel-headers/generic/include -I$RUNLIMIT_INCLUDE/kernel-headers/${MACHTYPE}/include" CC="musl-gcc -static -Os" make $@
